### ISSUE TITLE
absensi nya bagaimmana?

### ISSUE THREAD

**Issue by rickysut** [Zx-Akito/AbsensiAPP#1]
@dimstry cara absensi bagaimana? apakah absen harus login dahulu? alur kerjanya bagaimana sebenarnya absensi ini ?

**Comment by Zx-Akito** [comment]
Untuk absen sebenarnya tidak perlu login, karena absen hanya dengan scan barcode saja. Login itu hanya untuk melihat data absen dari siswa tersebut.

note:
Absensi App dan abseni Web beda ya, karena absensi web hanya digunakan untuk absensi nya saja. Tapi data absensi tersebut langsung masuk ke Absensi Web karena memiliki database yang sama.
